apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zv8yp7oer-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zv8yp7oer-java-springboot-gitops